version: "3.9"

services:
  database:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=cad'
      - 'POSTGRES_PASSWORD=cad'
      - 'POSTGRES_DB=clojure-api-db'
      - "POSTGRES_INITDB_ARGS='--encoding=UTF-8'"